services:
  front:
    image: nginx:1.27.0-alpine3.19
    container_name: construction-front
    depends_on:
      - web
      - api
    ports:
      - 8080:80
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf
  web:
    image: node:22.3.0-alpine3.19
    container_name: construction-web
    depends_on:
      - api
    volumes:
      - ./web:/app
    working_dir: /app
    command: ["npm", "start"]
  api:
    build: api
    container_name: construction-api
    volumes:
      - ./api/construction:/app
    depends_on:
      - postgres
    environment:
      - PRICE_M2_DOMAIN=*
      - PRICE_M2_DB_NAME=postgres
      - PRICE_M2_DB_USER=postgres
      - PRICE_M2_DB_PASSWORD=postgres
      - PRICE_M2_DB_HOST=postgres
      - PRICE_M2_DB_PORT=5432
    ports:
      - 8000:80
  postgres:
    image: postgres:16.3-alpine3.19
    container_name: construction-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./api/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
