# Generated by Django 5.0.6 on 2024-06-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alcaldia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsoConstruccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CatastroInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(db_index=True, max_length=32),
                ),
                ("superficie_terreno", models.FloatField()),
                ("superficie_construccion", models.FloatField()),
                ("valor_suelo", models.FloatField()),
                ("subsidio", models.FloatField()),
                (
                    "alcaldia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="price_m2.alcaldia",
                    ),
                ),
                (
                    "uso_construccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="price_m2.usoconstruccion",
                    ),
                ),
            ],
        ),
    ]
