name: PriceM2 API CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./api
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install --no-cache --no-root
    - name: Check code style
      working-directory: ./api
      run: |
        poetry run pre-commit run --all-files
    - name: Run Tests
      working-directory: ./api/construction
      run: |
        poetry run coverage run --source=price_m2 --omit='*migrations*' manage.py test
    - name: Validate Coverage
      working-directory: ./api/construction
      run: |
        poetry run coverage report -m --skip-covered --skip-empty --fail-under=90
